import { chromium, devices } from '@playwright/test';
const [,, base, out] = process.argv;
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices['Pixel 7'] });
const p = await ctx.newPage();
await p.goto(`${base}/fr/produit/thermomix-tm7`);
await p.getByRole('button', { name: /ajouter au panier/i }).click();
await p.waitForURL(/panier/);
await p.goto(`${base}/fr/produit/varoma-xl-steam-set`);
await p.getByRole('button', { name: /ajouter au panier/i }).click();
await p.waitForURL(/panier/);
await p.waitForTimeout(2000);
await p.screenshot({ path: out, fullPage: true });
await b.close();
console.log('ok', out);
